version: '3'
services:
  mysql-crud:
    container_name: mysql-crud
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mycrud
    volumes:
      - /home/diego/Escritorio/proyecto-crud-prueba/data/:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - net-crud
    restart: always

  crud-node:
    container_name: crud-node
    image: crudnode:v3
    ports:
      - 3000:3000
    restart: always
    networks:
      - net-crud
    depends_on:
      - mysql-crud
networks:
  net-crud: